num_classes: 50
image_size: 320x320
label_map: {
    1: apel_busuk,
    2: apel_segar,
    3: ayam_busuk,
    4: ayam_segar,
    5: bayam_busuk,
    6: bayam_segar,
    7: brokoli_busuk,
    8: brokoli_segar,
    9: buncis_busuk,
    10: buncis_segar,
    11: jagung_busuk,
    12: jagung_segar,
    13: jamur_busuk,
    14: jamur_segar,
    15: jeruk_busuk,
    16: jeruk_segar,
    17: kacangpanjang_busuk,
    18: kacangpanjang_segar,
    19: kangkung_busuk,
    20: kangkung_segar,
    21: kentang_busuk,
    22: kentang_segar,
    23: kubis_busuk,
    24: kubis_segar,
    25: labusiam_busuk,
    26: labusiam_segar,
    27: lemon_busuk,
    28: lemon_segar,
    29: naga_busuk,
    30: naga_segar,
    31: nanas_busuk,
    32: nanas_segar,
    33: pear_busuk,
    34: pear_segar,
    35: sapi_busuk,
    36: sapi_segar,
    37: sawihijau_busuk,
    38: sawihijau_segar,
    39: sawiputih_busuk,
    40: sawiputih_segar,
    41: tahu_busuk,
    42: tahu_segar,
    43: tauge_busuk,
    44: tauge_segar,
    45: tempe_busuk,
    46: tempe_segar,
    47: terong_busuk,
    48: terong_segar,
    49: wortel_busuk,
    50: wortel_segar,
}

